# Generated by Django 2.2.6 on 2019-11-25 11:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(max_length=40)),
                ('itemDescription', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('endTime', models.DateField(max_length=8)),
                ('itemPicture', models.ImageField(default='default.jpg', upload_to='item_pics')),
                ('date_listed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Isopen', models.BooleanField()),
                ('biddings', models.CharField(max_length=100000)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
