# Generated by Django 2.2.6 on 2019-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currentBid',
            field=models.CharField(default=10, max_length=100000),
            preserve_default=False,
        ),
    ]
