# Generated by Django 2.2.6 on 2019-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0003_auto_20191125_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Isopen',
            field=models.BooleanField(null=True),
        ),
    ]
