# Generated by Django 2.2.6 on 2019-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0004_auto_20191125_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currentBid',
            field=models.IntegerField(blank=True),
        ),
    ]
