# Generated by Django 2.2.6 on 2019-11-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0007_auto_20191126_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='AmountBid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
