# Generated by Django 2.2.6 on 2019-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0008_bid_amountbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currentBid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
