# Generated by Django 2.2.6 on 2019-11-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0009_auto_20191127_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currentBid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
