# Generated by Django 2.2.6 on 2019-11-27 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0010_auto_20191127_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
