# Generated by Django 2.2.6 on 2019-11-27 17:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0013_auto_20191127_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='AmountBid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='currentBid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
