# Generated by Django 2.2.6 on 2019-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0014_auto_20191127_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Isopen',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
